package com.emotion.cus.mapper;

import com.emotion.cus.po.CusUser;
import com.emotion.cus.po.CusUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    long countByExample(CusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int deleteByExample(CusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int insert(CusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int insertSelective(CusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    List<CusUser> selectByExample(CusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    CusUser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") CusUser record, @Param("example") CusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int updateByExample(@Param("record") CusUser record, @Param("example") CusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int updateByPrimaryKeySelective(CusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like_user
     *
     * @mbg.generated Wed Mar 27 19:07:58 CST 2019
     */
    int updateByPrimaryKey(CusUser record);
}